# Use postgres/example user/password credentials
version: '3'

services:
  postgresql:
    image: postgres:16.3
    container_name: postgres-nestjs
    ports:
      - 5432:5432
    volumes:
      - E:/postgres/nestjs-start:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=test
    command: postgres
    restart: always

  redis:
    image: redis:alpine3.14
    container_name: redis-nestjs
    ports:
      - "6379:6379"
